version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  initdb:
      image: python:3.8
      depends_on:
        - postgres
      volumes:
        - .:/app
      working_dir: /app
      command: sh -c "pip install -r requirements.txt && python create_psql_database.py"

volumes:
  postgres_data: